#pragma once

#include <vector>
#include <string>

enum class SCRIPT_TYPE
{
	ARBITERSCRIPT,
	ARCHONEFFECTSCRIPT,
	ARCHONSCRIPT,
	BUILDINGMGR,
	BUILDINGSCRIPT,
	BULLETSCRIPT,
	BUTTONSCRIPT,
	CAMERASCRIPT,
	CARRIERSCRIPT,
	CORSAIRSCRIPT,
	DARKARCHONSCRIPT,
	DARKTEMPLARSCRIPT,
	DRAGOONSCRIPT,
	GASSCRIPT,
	HIGHTEMPLARSCRIPT,
	ICONSCRIPT,
	INTERCEPTORSCRIPT,
	LOADSCIPRTMGR,
	MARKSCRIPT,
	MINERALSCRIPT,
	MONSTERSCRIPT,
	MOUSESCRIPT,
	MUZZLESCRIPT,
	NEXUSSCRIPT,
	NUMBERMGR,
	NUMBERSCRIPT,
	OBSERVERSCRIPT,
	PLANETSCRIPT,
	PLAYERSCRIPT,
	PORTRAITSCRIPT,
	PROBESCRIPT,
	PRODUCESCRIPT,
	PROTOSSUISCRIPT,
	REAVERSCRIPT,
	RESOURCESCRIPT,
	SCOUTSCRIPT,
	SECLECTSCRIPT,
	SHUTTLESCRIPT,
	SKILLMGR,
	SKILLSCRIPT,
	STATUSSCRIPT,
	TILEMGR,
	TILESCRIPT,
	UIMGR,
	UNITEFFECTSCRIPT,
	UNITMGR,
	UNITSCRIPT,
	UNITSHADSCRIPT,
	UPGRADEMGR,
	WIREFRAMESCRIPT,
	ZEALOTSCRIPT,
	END,
};

using namespace std;

class CScript;

class CScriptMgr
{
public:
	static void GetScriptInfo(vector<wstring>& _vec);
	static CScript * GetScript(const wstring& _strScriptName);
	static const wchar_t * GetScriptName(CScript * _pScript);
};
